sudo: required
dist: trusty
env:
  global:
  - secure: 0FhnDlTI+0W9mR/F8b1lKF82unzsFGXUlQxDqoWeq9TaipxfnGtloAYHR845xkW25SgAfMuiAZWkyN7VguiUJsqjwjq6n9240I6p8AQJMwAS00OEmbymAhj89JY7ujKy5IOYANxKMWeE2dKhUz/6XIRly6qTSzXR/SD8MEuN+66wqauHyw71pFo01w6CQMTwtA9CoT6CI1FIz71GtqjFdklblO+ughqOzwb/q+cl4l4YF/jGIZdhVXgsar2vv2FWuAc8erBvnEt/B/KR+ZzgWL4vvXbUASfzPjx7/UaAwc1UcksIuzmlFcOxXGBoyRGlMkV8HlM/CrDQFZxLkeiGtfMuEYDFFTNxyWdIu3DSjSKCO0IF4xln8/9Ej6RUJFmvuZ2RGZ+frTQ7gP0sr4IzH4lsTekqtU4DyeX6Ua8EFoJbWKyGFfOCmirL1SK4lFta0lGaOPdSjuWVeCKI2pr3ldBx/DuHFaeccH2r1VOY+ibTBItlSZ7eeQlBRBm6FoAdRqD21VGphlLQiN82nzTtzAHL/YqRnNr4pbGDItxSE22cT8Al/SJsC7I+bFwtwPORKclk/XvNY7yMlvX1c/V5c+vHC91dLE+FnnOocONzLIvJoGFpc5VO/7OHOSAH+Cueiol+ZWUQG5DXTmCGxrs5xWXE7zbu1WRTVH/017OYKig=
  - secure: OCnzIzeZ7td/mq0TvRFw/cwjTedb3EybIg405ljc8qQYg8I3EnJi54dbmBkeSMmhJK7wSz1NI+cS0ek69qnsEoTzEv5Kf2i7oW+1AtaLUo7HzvkMQSVt7VJ/dBG8LQTTeiDZ8YQlDskpXZiYLyb4hSW1GsECLqINiJeHSo7t0cvnjtzQgi3ZaVPRmFW4IVxtAW6ADgvpeufQAelP85Ofb4GFaMaFTf0P+HX9dhgNr/rs9dKAms3tmS9QNwmXMiWf/ePj9i8/F9GxlbQY20jipM3vp7vc7107IGB4PZvKtRjQQf/KhUZrttp1ExJC1UnioebNplG9oUYSKFm+PThi1yZdgoG5d7oNiy4LdW5+43IspYH9wGj2Qh0GLjylFr9489vHQqZAIohhXYjaxzJO+n1txb6F0Z80fpyyfl2IqOrWoQNlv8Akq7R19Px24+lAwYsa/ff4UwcTD8ozq2kTCyjt2YYcmV1zMK3TRCnzBaIjI1kzpLCENixT+9lImk0rVrDL5jayv+D5FUf/5yoISWQCEyYvQgIY1rK3GD75b9UJQ3KgEZaARPSzG3IiYCsLfM/uCH7DHOIrKMrp8PVcLQg4o46218t3dJdAed11WEEZOkskgo/oO98UopM4YuIrzshnD+gFrm8Vb+mYfh+3oh0av1XieK0YGuTKuox/Sl4=
  matrix:
  - ARCH=arm
  - ARCH=amd64
before_script:
- docker run --rm --privileged multiarch/qemu-user-static:register
- wget https://github.com/multiarch/qemu-user-static/releases/download/v2.12.0/qemu-arm-static
script:
- "./build.sh"
